### ISSUE TITLE
GramFuzzer import error

### ISSUE THREAD

**Issue by s4bu** [mseclab/PyJFuzz#8]
Hi I am getting following error:

python test.py
Traceback (most recent call last):
File "test.py", line 25, in 
from test import test_pjf_factory
File "/root/fuzzer/PyJFuzz/test/test_pjf_factory.py", line 24, in 
from pyjfuzz.core.pjf_configuration import PJFConfiguration
File "/root/fuzzer/PyJFuzz/pyjfuzz/core/pjf_configuration.py", line 32, in 
from .pjf_grammar import generate_json
File "/root/fuzzer/PyJFuzz/pyjfuzz/core/pjf_grammar.py", line 25, in 
from gramfuzz import GramFuzzer
ImportError: cannot import name GramFuzzer

**Comment by s4bu** [comment]
I fixed it by manually installing the latest copy of gramfuzz ==1.2.1

**Comment by fex** [comment]
Thanks for the hint, but it did not help me:

```
$ sudo pip install gramfuzz==1.2.1
...
Successfully installed gramfuzz-1.2.1
```

Still same output...

```
$ python test.py 
Traceback (most recent call last):
  File "test.py", line 25, in <module>
    from test import test_pjf_factory
  File "/data/work/tools/PyJFuzz/test/test_pjf_factory.py", line 24, in <module>
    from pyjfuzz.core.pjf_configuration import PJFConfiguration
  File "/data/work/tools/PyJFuzz/pyjfuzz/core/pjf_configuration.py", line 32, in <module>
    from .pjf_grammar import generate_json
  File "/data/work/tools/PyJFuzz/pyjfuzz/core/pjf_grammar.py", line 25, in <module>
    from gramfuzz import GramFuzzer
ImportError: cannot import name GramFuzzer
```
Any other idea?

**Comment by fex** [comment]
What I did is:

Change in `pjf_grammar.py`

`from gramfuzz import GramFuzzer`
to
`from gramfuzz import *`

Looks like it works now...
